# 🐼 Pandas Basics

---

**What is Pandas?**

Pandas is a Python library that lets you work with **tables of data** — just like Excel, but with code.

Think of it this way:
- 📊 **Excel** → you click to filter, sort, and calculate
- 🐼 **Pandas** → you write a few lines of code to do the same (and much more!)

**Topics in this notebook:**
1. Installing & Importing Pandas
2. Series — A Single Column
3. DataFrame — A Full Table
4. Creating a DataFrame
5. Viewing Data
6. Selecting Rows & Columns
7. Filtering Data
8. Adding & Removing Columns
9. Sorting Data
10. Summary Statistics
11. Handling Missing Data
12. Grouping & Aggregation
13. Reading a CSV File
14. Mini Business Project

---
## 1. 📦 Installing & Importing Pandas

In [ ]:
# If pandas is not installed, run this line first (remove the # sign)
# !pip install pandas

# Import pandas — we give it a short nickname 'pd'
import pandas as pd

print("✅ Pandas imported successfully!")
print(f"Pandas version: {pd.__version__}")

✅ Pandas imported successfully!
Pandas version: 3.0.2

---
## 2. 📊 Series — A Single Column

A **Series** is like a single column in Excel — it holds one list of values with an index (row number).

```
Index    Value
  0      12000
  1      15000
  2       9800
```

In [ ]:
# Create a simple Series from a list

daily_sales = pd.Series([12000, 15000, 9800, 22000, 18300])
print(daily_sales)

0    12000
1    15000
2     9800
3    22000
4    18300
dtype: int64

In [ ]:
# Series with custom index labels

branch_sales = pd.Series(
    [150000, 210000, 98000, 175000],
    index=["New Road", "Thamel", "Patan", "Bhaktapur"]
)

print(branch_sales)
print()

# Access by label
print(f"Thamel sales: Rs. {branch_sales['Thamel']:,}")

# Basic stats on a Series
print(f"\nTotal  : Rs. {branch_sales.sum():,}")
print(f"Average: Rs. {branch_sales.mean():,.0f}")
print(f"Highest: Rs. {branch_sales.max():,}")

New Road     150000
Thamel       210000
Patan         98000
Bhaktapur    175000
dtype: int64

Thamel sales: Rs. 210,000

Total  : Rs. 633,000
Average: Rs. 158,250
Highest: Rs. 210,000

---
## 3. 🗃️ DataFrame — A Full Table

A **DataFrame** is a full table with **rows and columns** — just like an Excel spreadsheet.

```
   Name         City       Salary
0  Ram Thapa    Kathmandu  45000
1  Sita Rai     Pokhara    52000
2  Hari Magar   Lalitpur   61000
```

- Each **column** is a Series
- All columns together make a DataFrame

---
## 4. ➕ Creating a DataFrame

In [ ]:
# Method 1: From a dictionary (most common way)
# Each key = column name, each value = list of data

data = {
    "Name"      : ["Ram Thapa", "Sita Rai", "Hari Magar", "Gita Shrestha", "Bikash KC"],
    "City"      : ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Kathmandu"],
    "Department": ["Sales", "Finance", "IT", "HR", "Sales"],
    "Salary"    : [45000, 52000, 78000, 41000, 49000],
    "Experience": [3, 5, 7, 2, 4]
}

df = pd.DataFrame(data)
print(df)

            Name        City Department  Salary  Experience
0      Ram Thapa   Kathmandu      Sales   45000           3
1       Sita Rai     Pokhara    Finance   52000           5
2     Hari Magar    Lalitpur         IT   78000           7
3  Gita Shrestha  Biratnagar         HR   41000           2
4      Bikash KC   Kathmandu      Sales   49000           4

In [ ]:
# Method 2: From a list of dictionaries
# Each dictionary = one row

products = [
    {"Product": "Laptop",    "Brand": "HP",      "Price": 85000, "Stock": 10},
    {"Product": "Mobile",    "Brand": "Samsung",  "Price": 45000, "Stock": 25},
    {"Product": "Tablet",    "Brand": "Xiaomi",   "Price": 35000, "Stock": 8},
    {"Product": "Headphone", "Brand": "JBL",      "Price": 8000,  "Stock": 40},
]

df_products = pd.DataFrame(products)
print(df_products)

     Product    Brand  Price  Stock
0     Laptop       HP  85000     10
1     Mobile  Samsung  45000     25
2     Tablet   Xiaomi  35000      8
3  Headphone      JBL   8000     40

---
## 5. 👀 Viewing Data

When you have a large dataset, you don't want to see all rows at once. These commands help you quickly explore the data.

In [ ]:
# Create a bigger employee dataset
data = {
    "Name"      : ["Ram", "Sita", "Hari", "Gita", "Bikash", "Priya", "Rohan", "Anita"],
    "City"      : ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Kathmandu", "Pokhara", "Butwal", "Lalitpur"],
    "Department": ["Sales", "Finance", "IT", "HR", "Sales", "Finance", "IT", "HR"],
    "Salary"    : [45000, 52000, 78000, 41000, 49000, 61000, 72000, 38000],
    "Experience": [3, 5, 7, 2, 4, 6, 8, None]
}
df = pd.DataFrame(data)

In [ ]:
# head() — shows first 5 rows (default)
df.head()

     Name        City Department  Salary  Experience
0     Ram   Kathmandu      Sales   45000         3.0
1    Sita     Pokhara    Finance   52000         5.0
2    Hari    Lalitpur         IT   78000         7.0
3    Gita  Biratnagar         HR   41000         2.0
4  Bikash   Kathmandu      Sales   49000         4.0

In [ ]:
# head(3) — shows first 3 rows
df.head(3)

   Name       City Department  Salary  Experience
0   Ram  Kathmandu      Sales   45000         3.0
1  Sita    Pokhara    Finance   52000         5.0
2  Hari   Lalitpur         IT   78000         7.0

In [ ]:
# tail() — shows last 5 rows
df.tail()

     Name        City Department  Salary  Experience
3    Gita  Biratnagar         HR   41000         2.0
4  Bikash   Kathmandu      Sales   49000         4.0
5   Priya     Pokhara    Finance   61000         6.0
6   Rohan      Butwal         IT   72000         8.0
7   Anita    Lalitpur         HR   38000         NaN

In [ ]:
# shape — how many rows and columns?
print(f"Rows    : {df.shape[0]}") # number of rows
print(f"Columns : {df.shape[1]}") #number of columns
print(f"Shape   : {df.shape}")

Rows    : 8
Columns : 5
Shape   : (8, 5)

In [ ]:
# columns — list of all column names
print(df.columns.tolist())
print(df.columns)

['Name', 'City', 'Department', 'Salary', 'Experience']
Index(['Name', 'City', 'Department', 'Salary', 'Experience'], dtype='str')

In [ ]:
# info() — data types and missing value summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   City        8 non-null      str
 2   Department  8 non-null      str
 3   Salary      8 non-null      int64
 4   Experience  7 non-null      float64
dtypes: float64(1), int64(1), str(3)
memory usage: 452.0 bytes

In [ ]:
# dtypes — data type of each column
print(df.dtypes)

Name              str
City              str
Department        str
Salary          int64
Experience    float64
dtype: object

---
## 6. 🎯 Selecting Rows & Columns

This is like selecting cells in Excel — but with code.

In [ ]:
# Select ONE column — returns a Series
df["Name"]

0       Ram
1      Sita
2      Hari
3      Gita
4    Bikash
5     Priya
6     Rohan
7     Anita
Name: Name, dtype: str

In [ ]:
# Select MULTIPLE columns — returns a DataFrame
df[["Name", "Department", "Salary"]]

     Name Department  Salary
0     Ram      Sales   45000
1    Sita    Finance   52000
2    Hari         IT   78000
3    Gita         HR   41000
4  Bikash      Sales   49000
5   Priya    Finance   61000
6   Rohan         IT   72000
7   Anita         HR   38000

In [ ]:
# Select rows by index number using iloc
# iloc = integer location

df.iloc[0]       # First row

Name                Ram
City          Kathmandu
Department        Sales
Salary            45000
Experience          3.0
Name: 0, dtype: object

In [ ]:
df.iloc[0:3]     # First 3 rows (rows 0, 1, 2)

In [ ]:
# Select a specific cell — iloc[row, column]
print(df.iloc[1, 0])    # Row 1, Column 0 = Name of second employee
print(df.iloc[2, 3])    # Row 2, Column 3 = Salary of third employee

Sita
78000

In [ ]:
df.loc[0,"Salary"]

np.int64(45000)

In [ ]:
df.loc[:,["city","salary"]]

In [ ]:
# Select rows by label using loc
# First set a meaningful index

df_indexed = df.set_index("Name")  #index is set to Name column
print(df_indexed.loc["Sita","Salary"])  # Row where Name = Sita
print(df_indexed)

52000
              City Department  Salary  Experience
Name
Ram      Kathmandu      Sales   45000         3.0
Sita       Pokhara    Finance   52000         5.0
Hari      Lalitpur         IT   78000         7.0
Gita    Biratnagar         HR   41000         2.0
Bikash   Kathmandu      Sales   49000         4.0
Priya      Pokhara    Finance   61000         6.0
Rohan       Butwal         IT   72000         8.0
Anita     Lalitpur         HR   38000         NaN

---
## 7. 🔍 Filtering Data

Filtering = showing only rows that match a condition.
This is like the **Filter** button in Excel!

In [ ]:
# Filter: Only employees in Kathmandu
# First df["City"] → select the column to compare
# Second df[...] → select the rows from the DataFrame that satisfy the condition

df[df["City"] == "Kathmandu"]
df["City"] == "Kathmandu"

     Name       City Department  Salary  Experience
0     Ram  Kathmandu      Sales   45000         3.0
4  Bikash  Kathmandu      Sales   49000         4.0

In [ ]:
# Filter: Only employees with salary above 50,000
df[df["Salary"] > 50000]

    Name      City Department  Salary  Experience
1   Sita   Pokhara    Finance   52000         5.0
2   Hari  Lalitpur         IT   78000         7.0
5  Priya   Pokhara    Finance   61000         6.0
6  Rohan    Butwal         IT   72000         8.0

In [ ]:
# Filter with TWO conditions
# & means AND  |  means OR

# Employees in Sales department AND salary > 45000
df[(df["Department"] == "Sales") & (df["Salary"] > 45000)]

     Name       City Department  Salary  Experience
4  Bikash  Kathmandu      Sales   49000         4.0

In [ ]:
# Filter: Employees in Kathmandu OR Pokhara
df[(df["City"] == "Kathmandu") | (df["City"] == "Pokhara")]

     Name       City Department  Salary  Experience
0     Ram  Kathmandu      Sales   45000         3.0
1    Sita    Pokhara    Finance   52000         5.0
4  Bikash  Kathmandu      Sales   49000         4.0
5   Priya    Pokhara    Finance   61000         6.0

In [ ]:
# isin() — filter by multiple values (cleaner way)
df[df["City"].isin(["Kathmandu", "Pokhara", "Lalitpur"])]

---
## 8. ➕ Adding & Removing Columns

In [ ]:
# Add a new column — Annual Salary
df["Annual Salary"] = df["Salary"] * 12
df[["Name", "Salary", "Annual Salary"]].head()

In [ ]:
# Add a column based on a condition
# If experience >= 5 years → Senior, else → Junior

df["Level"] = df["Experience"].apply(lambda x: "Senior" if x >= 5 else "Junior")
df[["Name", "Experience", "Level"]].head(8)

In [ ]:
# Add bonus column — 10% of salary for Senior, 5% for Junior
df["Bonus"] = df.apply(
    lambda row: row["Salary"] * 0.10 if row["Level"] == "Senior" else row["Salary"] * 0.05,
    axis=1
)
df[["Name", "Salary", "Level", "Bonus"]].head(8)

In [ ]:
# Remove a column using drop()
df_clean = df.drop(columns=["Annual Salary", "Bonus"])
df_clean.head()

---
## 9. 🔃 Sorting Data

Like clicking a column header to sort in Excel!

In [ ]:
# Sort by Salary — lowest first (ascending)
df.sort_values("Salary").head()

In [ ]:
# Sort by Salary — highest first (descending)
df.sort_values("Salary", ascending=False).head()

In [ ]:
# Sort by multiple columns — Department first, then Salary
df.sort_values(["Department", "Salary"], ascending=[True, False])[["Name", "Department", "Salary"]]

---
## 10. 📈 Summary Statistics

Get quick statistics on your data — like the Data Analysis ToolPak in Excel.

In [ ]:
# describe() — summary statistics for all numeric columns
df[["Salary", "Experience"]].describe()

In [ ]:
# Individual statistics on a column

print(f"Mean Salary   : Rs. {df['Salary'].mean():,.0f}")
print(f"Median Salary : Rs. {df['Salary'].median():,.0f}")
print(f"Max Salary    : Rs. {df['Salary'].max():,}")
print(f"Min Salary    : Rs. {df['Salary'].min():,}")
print(f"Total Payroll : Rs. {df['Salary'].sum():,}")
print(f"Std Deviation : Rs. {df['Salary'].std():,.0f}")

In [ ]:
# value_counts() — count how many times each value appears
# Like COUNTIF in Excel!

print("Employees per Department:")
print(df["Department"].value_counts())

print("\nEmployees per City:")
print(df["City"].value_counts())

---
## 11. 🚫 Handling Missing Data

Real-world data always has missing values. Pandas makes it easy to find and fix them.

In [ ]:
import numpy as np

# Create a dataset with missing values (NaN = Not a Number = empty cell)
data_missing = {
    "Name"  : ["Ram", "Sita", "Hari", "Gita", "Bikash"],
    "City"  : ["Kathmandu", None, "Lalitpur", "Biratnagar", None],
    "Salary": [45000, 52000, np.nan, 41000, 49000],
    "Phone" : ["98XXXXXXXX", "97XXXXXXXX", None, None, "98XXXXXXXX"]
}

df_missing = pd.DataFrame(data_missing)
df_missing

In [ ]:
# isnull() — show which cells are missing
df_missing.isnull()

In [ ]:
# Count missing values per column
print(df_missing.isnull().sum())

In [ ]:
# Option 1: Fill missing values with a default value
df_filled = df_missing.copy()
df_filled["City"]   = df_filled["City"].fillna("Unknown")
df_filled["Salary"] = df_filled["Salary"].fillna(df_filled["Salary"].mean())  # fill with average
df_filled["Phone"]  = df_filled["Phone"].fillna("Not Provided")
df_filled

In [ ]:
# Option 2: Drop rows that have ANY missing value
df_dropped = df_missing.dropna()
df_dropped

---
## 12. 📦 Grouping & Aggregation

**groupby()** is like a Pivot Table in Excel — it groups rows by a category and calculates totals, averages, etc.

In [ ]:
# Average salary by Department
df.groupby("Department")["Salary"].mean().round(0)

In [ ]:
# Total salary cost per Department
df.groupby("Department")["Salary"].sum()

In [ ]:
# Multiple statistics at once using agg()
df.groupby("Department")["Salary"].agg(["count", "mean", "min", "max"]).round(0)

In [ ]:
# Group by City — count employees and average salary
df.groupby("City").agg(
    Employee_Count=("Name", "count"),
    Avg_Salary=("Salary", "mean"),
    Total_Salary=("Salary", "sum")
).round(0)

---
## 13. 📂 Reading a CSV File

In real business, data comes from CSV files (Excel exports, database exports, etc.).
Pandas can read them in one line!

In [ ]:
# First, let's CREATE a sample CSV file to practice with

sales_data = {
    "Date"      : ["2025-01-01", "2025-01-02", "2025-01-03", "2025-01-04", "2025-01-05",
                   "2025-01-06", "2025-01-07", "2025-01-08", "2025-01-09", "2025-01-10"],
    "Branch"    : ["Thamel", "Patan", "Thamel", "Bhaktapur", "Patan",
                   "Thamel", "Bhaktapur", "Patan", "Thamel", "Bhaktapur"],
    "Product"   : ["Laptop", "Mobile", "Tablet", "Laptop", "Headphone",
                   "Mobile", "Tablet", "Laptop", "Headphone", "Mobile"],
    "Quantity"  : [2, 5, 3, 1, 8, 4, 2, 3, 6, 7],
    "Unit_Price": [85000, 45000, 35000, 85000, 8000, 45000, 35000, 85000, 8000, 45000]
}

df_sales = pd.DataFrame(sales_data)
df_sales["Total"] = df_sales["Quantity"] * df_sales["Unit_Price"]

# Save to CSV
df_sales.to_csv("sales.csv", index=False)
print("✅ sales.csv file created!")

In [ ]:
# Now READ the CSV file back
df_from_csv = pd.read_csv("sales.csv")

print(f"Shape: {df_from_csv.shape}")
df_from_csv.head()

In [ ]:
# Analyze the CSV data

print("--- Sales Summary ---")
print(f"Total Revenue : Rs. {df_from_csv['Total'].sum():,}")
print(f"Total Items   : {df_from_csv['Quantity'].sum()}")
print(f"Avg Order     : Rs. {df_from_csv['Total'].mean():,.0f}")

print("\n--- Revenue by Branch ---")
print(df_from_csv.groupby("Branch")["Total"].sum().sort_values(ascending=False))

In [ ]:
# Save results to a new CSV
branch_report = df_from_csv.groupby("Branch")["Total"].sum().reset_index()
branch_report.columns = ["Branch", "Total_Revenue"]
branch_report.to_csv("branch_report.csv", index=False)
print("✅ branch_report.csv saved!")
print(branch_report)

---
## 14. 💼 Mini Business Project

**Scenario:** You are the Data Analyst at a Daraz Nepal office.
You have one month of order data. Your manager wants a complete sales report.

Tasks:
1. Load and explore the data
2. Find total revenue
3. Find best-selling product
4. Find top city by orders
5. Flag high-value orders (above Rs. 50,000)

In [ ]:
# Step 1: Create the dataset

orders = {
    "Order_ID" : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Customer" : ["Ram", "Sita", "Hari", "Gita", "Bikash", "Priya", "Rohan", "Anita", "Suresh", "Mina"],
    "City"     : ["Kathmandu", "Pokhara", "Kathmandu", "Biratnagar", "Lalitpur",
                  "Kathmandu", "Pokhara", "Lalitpur", "Kathmandu", "Biratnagar"],
    "Product"  : ["Laptop", "Mobile", "Mobile", "Laptop", "Tablet",
                  "Headphone", "Laptop", "Mobile", "Tablet", "Headphone"],
    "Quantity" : [1, 2, 1, 1, 3, 5, 2, 1, 2, 4],
    "Price"    : [85000, 45000, 45000, 85000, 35000, 8000, 85000, 45000, 35000, 8000]
}

df_orders = pd.DataFrame(orders)
df_orders["Revenue"] = df_orders["Quantity"] * df_orders["Price"]

print("✅ Dataset created!")
df_orders

In [ ]:
# Step 2: Total Revenue
total_revenue = df_orders["Revenue"].sum()
total_orders = len(df_orders)
print(f"Total Orders  : {total_orders}")
print(f"Total Revenue : Rs. {total_revenue:,}")

In [ ]:
# Step 3: Best-selling product by revenue
product_revenue = df_orders.groupby("Product")["Revenue"].sum().sort_values(ascending=False)
print("Revenue by Product:")
print(product_revenue)

In [ ]:
# Step 4: Top city by number of orders
city_orders = df_orders["City"].value_counts()
print("Orders by City:")
print(city_orders)
print(f"\n🏆 Top City: {city_orders.index[0]} with {city_orders.iloc[0]} orders")

In [ ]:
# Step 5: Flag high-value orders
df_orders["Order_Type"] = df_orders["Revenue"].apply(
    lambda x: "🔥 High Value" if x >= 50000 else "Regular"
)

print("All Orders with Type:")
df_orders[["Order_ID", "Customer", "Product", "Revenue", "Order_Type"]]

In [ ]:
# Final Report Summary
print("=" * 45)
print("   DARAZ NEPAL — MONTHLY SALES REPORT")
print("=" * 45)
print(f"Total Orders        : {total_orders}")
print(f"Total Revenue       : Rs. {total_revenue:,}")
print(f"Average Order Value : Rs. {df_orders['Revenue'].mean():,.0f}")
print(f"Top Product         : {product_revenue.index[0]}")
print(f"Top City            : {city_orders.index[0]}")
print(f"High Value Orders   : {(df_orders['Order_Type'] == '🔥 High Value').sum()}")
print("=" * 45)

---
## 🎉 Summary — Pandas Cheat Sheet

| Task | Code | Excel Equivalent |
|------|------|------------------|
| Create table | `pd.DataFrame(data)` | Type data in sheet |
| First 5 rows | `df.head()` | Scroll to top |
| Last 5 rows | `df.tail()` | Scroll to bottom |
| Shape | `df.shape` | Check row/col count |
| Column names | `df.columns` | Look at header row |
| Select column | `df["Name"]` | Click column |
| Select row | `df.iloc[0]` | Click row |
| Filter data | `df[df["City"] == "KTM"]` | Filter button |
| Add column | `df["New"] = ...` | Add new column |
| Delete column | `df.drop(columns=[...])` | Delete column |
| Sort | `df.sort_values("Col")` | Sort A→Z |
| Sum | `df["Col"].sum()` | SUM formula |
| Average | `df["Col"].mean()` | AVERAGE formula |
| Count unique | `df["Col"].value_counts()` | COUNTIF |
| Group by | `df.groupby("Col")` | Pivot Table |
| Read CSV | `pd.read_csv("file.csv")` | Open file |
| Save CSV | `df.to_csv("file.csv")` | Save As CSV |
| Missing values | `df.isnull().sum()` | Find blank cells |
| Fill missing | `df.fillna(value)` | Replace blanks |

---
*SkillShikshya — Business Data Analytics with AI | Kathmandu, Nepal*